# Generated by Django 3.0.8 on 2022-10-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemsHearth',
            new_name='ProblemHearth',
        ),
    ]
