# Generated by Django 3.0.8 on 2022-10-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saude_app', '0002_auto_20221011_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemhearth',
            name='code',
            field=models.ForeignKey(default='0001', on_delete=django.db.models.deletion.CASCADE, to='saude_app.Customer'),
        ),
    ]
