# Generated by Django 3.0.8 on 2022-10-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude_app', '0003_problemhearth_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemhearth',
            old_name='code',
            new_name='code_costumer',
        ),
    ]
